In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.pyplot import MultipleLocator
from math import sqrt
from numpy import concatenate
from pandas import read_csv, DataFrame, concat
from datetime import datetime
from sklearn.metrics import mean_squared_error

from sklearn.preprocessing import MinMaxScaler, StandardScaler

import keras.backend as K
from keras.layers import Multiply
from keras.models import Sequential ,Model
from keras.layers import Dense , Input , Reshape , Flatten ,Permute , Lambda , RepeatVector ,Conv1D , MaxPooling1D , Dropout, Bidirectional, Activation
from keras.layers import GRU, LSTM
from keras.utils.vis_utils import plot_model
from keras.optimizers import SGD,Adam

Using TensorFlow backend.

In [2]:
data_1 = pd.read_csv('force1500_步长10_混合注意力.csv')
data_1.head()

data_1.describe()

              real          pre
count  4500.000000  4500.000000
mean   4995.377778  5029.888889
std     739.526419   720.598117
min    3080.000000  3360.000000
25%    4460.000000  4520.000000
50%    4970.000000  5030.000000
75%    5530.000000  5530.000000
max    7400.000000  7100.000000

In [3]:
data_1 = pd.read_csv('force1500_步长20_混合注意力.csv')
data_1.head()

data_1.describe()

              real          pre
count  4500.000000  4500.000000
mean   4995.377778  5005.237778
std     739.526419   749.675168
min    3080.000000  3180.000000
25%    4460.000000  4450.000000
50%    4970.000000  4990.000000
75%    5530.000000  5560.000000
max    7400.000000  7070.000000

In [4]:
data_1 = pd.read_csv('force1500_步长30_混合注意力.csv')
data_1.head()

data_1.describe()

              real          pre
count  4500.000000  4500.000000
mean   4995.377778  4991.546667
std     739.526419   743.188680
min    3080.000000  3140.000000
25%    4460.000000  4440.000000
50%    4970.000000  5000.000000
75%    5530.000000  5520.000000
max    7400.000000  7030.000000

In [5]:
data_1 = pd.read_csv('force1500_步长40_混合注意力.csv')
data_1.head()

data_1.describe()

              real          pre
count  4500.000000  4500.000000
mean   4995.377778  5002.797778
std     739.526419   711.605986
min    3080.000000  3310.000000
25%    4460.000000  4520.000000
50%    4970.000000  4970.000000
75%    5530.000000  5510.000000
max    7400.000000  6830.000000

In [6]:
data_1 = pd.read_csv('force2500_步长10_混合注意力.csv')
data_1.head()

data_1.describe()

              real          pre
count  4500.000000  4500.000000
mean   4958.360000  4971.491111
std     284.230847   240.961757
min    4290.000000  4400.000000
25%    4740.000000  4780.000000
50%    4980.000000  4970.000000
75%    5170.000000  5150.000000
max    5700.000000  5550.000000

In [7]:
data_1 = pd.read_csv('force2500_步长20_混合注意力.csv')
data_1.head()

data_1.describe()

              real          pre
count  4500.000000  4500.000000
mean   4958.360000  4959.824444
std     284.230847   242.220942
min    4290.000000  4390.000000
25%    4740.000000  4760.000000
50%    4980.000000  4970.000000
75%    5170.000000  5150.000000
max    5700.000000  5470.000000

In [8]:
data_1 = pd.read_csv('force2500_步长30_混合注意力.csv')
data_1.head()

data_1.describe()

              real          pre
count  4500.000000  4500.000000
mean   4958.360000  4969.395556
std     284.230847   243.479426
min    4290.000000  4340.000000
25%    4740.000000  4780.000000
50%    4980.000000  4950.000000
75%    5170.000000  5170.000000
max    5700.000000  5470.000000

In [9]:
data_1 = pd.read_csv('force2500_步长40_混合注意力.csv')
data_1.head()

data_1.describe()

             real           pre
count  4500.000000  4500.000000
mean   4958.360000  4971.284444
std     284.230847   243.792540
min    4290.000000  4360.000000
25%    4740.000000  4770.000000
50%    4980.000000  4960.000000
75%    5170.000000  5180.000000
max    5700.000000  5540.000000